### ISSUE TITLE
como hacer una evaluación 

### ISSUE THREAD

**Issue by galvi45** [miltonlab/sedd#2]
Luego que creo una evaluación y la asigno al evaluado con fechas de inicio y cierre, asi como el cuestionario. ¿Como hago para que el evaluador responda el cuestionario?

**Comment by miltonlab** [comment]
El evaluador debe estar en el PeriodoAcademico que sea el PeriodoAcademico ativo en el objeto Configuracion

**Comment by galvi45** [comment]
ok, ya pude realizar una evaluación todo lo estoy haciendo desde la administracion de django, por casualidad no hay un template que responda las preguntas de un cuestionario asignado a una evaluacion.

**Comment by miltonlab** [comment]
te refieres en el mismo admin?

**Comment by galvi45** [comment]
si

**Comment by galvi45** [comment]
si,

**Comment by miltonlab** [comment]
No eso no existe pero sería un buen agregado

**Comment by galvi45** [comment]
buenos dias! que tal como estas?,  
1.- Quisiera saber cual es la razon de uso de itempregunta y su funcion, 

2.- Por otro lado en la tabla contestacion agregue  este campo para la respuesta dado que las respuestas son de seleccion.
    respuesta_choices = (
        (1, 'Actitud No manifiesta'),
        (2, 'Deficient'e),
        (3, 'Necesita Mejorar'),
        (4, 'Cumple Expectativas'),
        (5, 'Supera Expectativas'),  
    )
    respuesta = models.IntegerField(
        choices=respuesta_choices,
        default=0
    )

Agradezco el apoyo

**Comment by galvi45** [comment]
que recomiendas para este tipo de respuestas

**Comment by miltonlab** [comment]
En realidad lo que estás haciendo para mi es un ItemPregunta lo cual permite que sea más abierto

**Comment by galvi45** [comment]
estoy en este momento trabajado con los templates, me estoy enredando un poco, porque veo que maneja el archivo controllers.py (views)
maneja  pares academicos, directores , asignaturas, carreras, areas, semestres, no estoy usando esas variables.
y como estoy trabjando solo con:
original                                             mi app  
PeriodoAcademico                          PeriodoLaboral
EstudiantePeriodoAcademico          EvaluadorPeriodoLaboral
DocentePeriodoAcademico             TrabajadorPeriodoLaboral
 y todo lo relaciona a la evaluacion
tinformate
evaluacion
cuestionario
seccion
preguntas

## contestaciones

solo si puedes detallar con respecto al archivo controlers.py, solo estudiante docente y periodo academico.

De verdad muy agradecido con el proyecto me ha permitido conocer mucho acerca de python y django.

**Comment by miltonlab** [comment]
@galvi45 sigamos halbando de esto acá por favor https://github.com/miltonlab/sedd/issues/3
